# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imprimeData/UI/impression.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_name.setStyleSheet("QLineEdit{\n"
"border:2px solid blue;}")
        self.line_name.setObjectName("line_name")
        self.verticalLayout.addWidget(self.line_name)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_last_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_last_name.setStyleSheet("QLineEdit{\n"
"border:2px solid blue;}")
        self.line_last_name.setObjectName("line_last_name")
        self.verticalLayout.addWidget(self.line_last_name)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setStyleSheet("QPushButton{\n"
"color:red;\n"
"font:Normal 17 bold;}")
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setStyleSheet("QPushButton{\n"
"color:green;\n"
"font:Normal 17 bold;}")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.btn_print_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_print_file.setStyleSheet("QPushButton{\n"
"color:brown;\n"
"font:Normal 17 bold;\n"
"}")
        self.btn_print_file.setObjectName("btn_print_file")
        self.horizontalLayout.addWidget(self.btn_print_file)
        self.btn_preview = QtWidgets.QPushButton(self.centralwidget)
        self.btn_preview.setStyleSheet("QPushButton{\n"
"color:blue;\n"
"font:Normal 17 bold;}")
        self.btn_preview.setObjectName("btn_preview")
        self.horizontalLayout.addWidget(self.btn_preview)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.view = QtWidgets.QTextEdit(self.centralwidget)
        self.view.setStyleSheet("QTextEdit{\n"
"border:2px solid blue;}")
        self.view.setObjectName("view")
        self.verticalLayout_2.addWidget(self.view)
        self.view_infos = QtWidgets.QTableWidget(self.centralwidget)
        self.view_infos.setObjectName("view_infos")
        self.view_infos.setColumnCount(3)
        self.view_infos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(8, 6, 16))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.view_infos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_infos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(82, 176, 178))
        self.view_infos.setHorizontalHeaderItem(2, item)
        self.view_infos.horizontalHeader().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.view_infos)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Name</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Last name</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Comments</span></p></body></html>"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.btn_save.setText(_translate("MainWindow", "save"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.btn_print_file.setText(_translate("MainWindow", "Print file"))
        self.btn_preview.setText(_translate("MainWindow", "Print preview"))
        self.view.setPlaceholderText(_translate("MainWindow", "talk about"))
        item = self.view_infos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.view_infos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LAST NAME"))
        item = self.view_infos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "COMMENTS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
